# Generated by Django 3.0.6 on 2020-06-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200609_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_business',
            new_name='is_seller',
        ),
    ]
