# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-26 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='damascuse', max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='syria', max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
