# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200526_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
