# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200526_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
