# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-26 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200526_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
