# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200526_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_closed',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_open',
            field=models.DateField(default=True),
        ),
    ]
