# Generated by Django 3.0.6 on 2020-06-01 14:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200601_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to=products.models.upload_product_file_loc),
        ),
    ]
