# Generated by Django 3.0.6 on 2020-06-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200601_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='free',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='user_required',
        ),
    ]
