# Generated by Django 3.0.6 on 2020-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_price',
            field=models.IntegerField(default=1),
        ),
    ]
