# Generated by Django 3.0.6 on 2020-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_price',
            field=models.IntegerField(default=0),
        ),
    ]
