# Generated by Django 3.0.6 on 2020-06-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200609_1907'),
        ('products', '0020_auto_20200606_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fee',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
        ),
    ]
